version: '3.9'
services:
  node1:
    hostname: node1
    image: ethereum/client-go:alltools-v1.10.15
    restart: on-failure
    working_dir: /root
    volumes:
      - ./.private/:/root
      - ./src:/root/src:ro
    networks:
      private:
        ipv4_address: 10.1.0.1
    command: /root/src/start_geth.sh node1 10.1.0.1

  node2:
    hostname: node2
    image: ethereum/client-go:alltools-v1.10.15
    restart: on-failure
    depends_on:
        - eth_private_node1
    ports:
      - "127.0.0.1:8545:8545"
      - "127.0.0.1:8546:8546"
    working_dir: /root
    volumes:
      - ./.private/:/root
      - ./src:/root/src:ro
    networks:
      private:
        ipv4_address: 10.1.0.2
    command: /root/src/start_geth.sh node2 10.1.0.2

  node3:
    hostname: node3
    image: ethereum/client-go:alltools-v1.10.15
    restart: on-failure
    depends_on:
        - eth_private_node1
    working_dir: /root
    volumes:
      - ./.private/:/root
      - ./src:/root/src:ro
    networks:
      private:
        ipv4_address: 10.1.0.3
    command: /root/src/start_geth.sh node3 10.1.0.3

networks:
  private:
    driver: bridge
    ipam:
     config:
       - subnet: 10.1.0.0/24
         gateway: 10.1.0.254
